### ISSUE TITLE
Create WireFrame for website

### ISSUE THREAD

**Issue by nk-mart** [nk-mart/edx-Group-Project--1#4]
Create a Wireframe for app. 

https://www.figma.com/file/wCTg6ohqD7vrsk9ZrVZU4R/Untitled?node-id=0%3A1&t=5hMti4QZgqgamvMM-1

**Comment by Lawzstopwar** [comment]
**Sketched functionality narrated in README.md**

**Comment by sumbal28** [comment]
To add more wireframing for project
